---

jobs:
- name: build-ship-it
  serial: true
  public: true
  plan:
  - aggregate:
    - get: alpine-docker-image
      trigger: true
      # params:
      #   skip_download: true
    - get: alpine-bash-git
      trigger: true
  - put: version
    params: {bump: minor}
  - put: alpine-bash-docker-image
    params:
      build: alpine-bash-git/
      tag: version/number
      tag_as_latest: true
  - put: alpine-bash-git
    params:
      repository: alpine-bash-git
      tag: version/number

resources:
- name: alpine-bash-git
  type: git
  source:
    uri: git@github.com:making/alpine-java-bash-git.git
    branch: master
    private_key: {{github-private-key}}

- name: alpine-bash-docker-image
  type: docker-image
  source:
    repository: {{docker-repo}}
    email: {{docker-email}}
    username: {{docker-username}}
    password: {{docker-password}}

- name: alpine-docker-image
  type: docker-image
  source:
    repository: openjdk
    tag: 8-jdk-alpine

- name: version
  type: semver
  source:
    uri: git@github.com:making/alpine-java-bash-git.git
    branch: version
    private_key: {{github-private-key}}
    file: version
    driver: git
    initial_version: 0.9.0
